version: 1.0.{build}

clone_folder: C:\gopath\src\github.com\BrianAllred\roboclicker

environment:
    matrix:
    - COMPILER: msys2
      PLATFORM: x64
      MSYS2_ARCH: x86_64
      MSYS2_DIR: msys64
      MSYSTEM: MINGW64
      BIT: 64
      GOPATH: C:\gopath
      QT_MSYS2: true
      QT_MSYS2_STATIC: true
      CGO_CXXFLAGS_ALLOW: .*
      CGO_LDFLAGS_ALLOW: .*
      CGO_CFLAGS_ALLOW: .*

install:
  - SET "PATH=C:\%MSYS2_DIR%\%MSYSTEM%\bin;C:\%MSYS2_DIR%\usr\bin;%GOPATH%\bin;c:\go\bin;%PATH%"
  - bash -lc "pacman -S --needed --noconfirm pacman-mirrors"
  - bash -lc "pacman -S --needed --noconfirm git"
  - bash -lc "pacman -Syu --noconfirm"
  - bash -lc "pacman -S --needed --noconfirm mingw-w64-x86_64-qt-creator mingw-w64-x86_64-qt5-static"  
  # Output useful info for debugging.
  - echo %PATH%
  - echo %GOPATH%
  - go version
  - go env

build_script:
  - cmd: go get -u -v github.com/therecipe/qt/cmd/...
  - cmd: qtsetup
  - cmd: qtdeploy build windows_64_static

artifacts:
  - path: 'C:\gopath\src\github.com\BrianAllred\roboclicker\deploy\windows\roboclicker.exe'