version: 2
jobs:
  build:
    docker:
      - image: therecipe/qt:linux
    working_directory: /home/user/work
    steps:
      - run:
          name: Install dependencies
          command: |
            apt-get -qq update && apt-get -qq -y install libx11-dev xorg-dev libxtst-dev libpng++-dev xcb libxcb-xkb-dev x11-xkb-utils libx11-xcb-dev libxkbcommon-x11-dev libxkbcommon-dev xsel xclip
      - run: go get -v -d github.com/BrianAllred/roboclicker
      - run:
          name: Build
          command: |
            cd src/github.com/BrianAllred/roboclicker && qtdeploy build linux
      - store_artifacts:
          path: src/github.com/BrianAllred/roboclicker/deploy/linux